avatar: https://i0.wp.com/dogtorrent-static.test.upcdn.net/img/2022/05/ded9a383f08cb7878fb7ab2b35df0fdb.jpg # 头像
background: # 既是博客的背景，又是文章默认头图
  path: https://i0.wp.com/dogtorrent-static.test.upcdn.net/img/2021/01/14e4dd7e2b871d8aba12b325346033c6.webp
  width: 1773
  height: 997
favicon:
  href: https://i0.wp.com/dogtorrent-static.test.upcdn.net/img/2021/01/39a0518da591445033837d016584371a.webp # 网站图标
  type: image/webp # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  
# 附加图标库 用于自定义字体 www.iconfont.cn 登录->创建项目->添加图标->获取链接
iconlib: //at.alicdn.com/t/font_1658687_huzf7hxhfdc.css # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

search: https://cn.bing.com/search?q=site:baidu.com # https://www.google.com/search?q={你的博客链接}

cdn: # 这里可以修改站点使用的库的CDN
  mdui:
    css: https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css
    js: https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/js/mdui.min.js
  lazysizes:
    js: https://cdn.jsdelivr.net/npm/lazysizes@5.3.2/lazysizes.min.js
  hljs:
    css: https://cdn.jsdelivr.net/npm/highlight.js@11.4.0/styles/base16/darcula.min.css
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/highlight.min.js
  prismjs:
    css: https://cdn.jsdelivr.net/npm/prismjs@1.27.0/themes/prism-okaidia.min.css
    js: 
      core: https://cdn.jsdelivr.net/npm/prismjs@1.27.0/components/prism-core.min.js
      autoloader: https://cdn.jsdelivr.net/npm/prismjs@1.27.0/plugins/autoloader/prism-autoloader.min.js
  fancybox:
    css: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  jquery:
    js: https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine@1.4.16/dist/Valine.min.js
  pjax:
    js: https://cdn.jsdelivr.net/npm/pjax@0.2.8/pjax.min.js
  topbar:
    js: https://cdn.jsdelivr.net/gh/buunguyen/topbar@0.1.3/topbar.min.js
  more:
    js: # 其他js链接，可以设置多个
      - https://cdn.jsdelivr.net/npm/prismjs@1.27.0/plugins/normalize-whitespace/prism-normalize-whitespace.min.js
      # - https://xxxxx.xxx/example1
      # - https://xxxxx.xxx/example2

menu:
  首页: 
    - /
    - icon-home
  归档: 
   - /archives
   - icon-container
  关于:
    - /about
    - icon-info-circle
  朋友: 
    - /friends

widgets:
- search
- social
- category
- tagcloud
- archive #settings: widgetAchive
# - recent_posts
# - link #settings: widgetLink

maxTagcloud: 0  # 0 表示不限制

social:
  GitHub:
    - https://github.com/
    - icon-gh
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
  Steam: 
    - https://steamcommunity.com/
    - icon-sbeam
    - rgb(0, 0, 139)
    - rgba(0, 0, 139, .15)
  微博:
    - https://weibo.com/
    - icon-weibo
    - rgb(247, 132, 34)
    - rgba(247, 132, 34, .15)
  # 哔哩哔哩:
  #   - https://bilibili.com/
  #   - icon-bilibili
  #   - rgb(231, 106, 141)
  #   - rgba(231, 106, 141, .15)
  邮件:
    - mailto:example@example.com
    - icon-email
    - rgb(16, 110, 190)
    - rgba(16, 110, 190, .15)
  订阅: 
    - https://baidu.com/
    - icon-subscribe
    - rgb(247, 132, 34)
    - rgba(247, 132, 34, .15)

site_verification: # 向搜索引擎验证你对站点的所有权，用于向搜索引擎提交 sitemap 和管理站点被搜索引擎收录的情况。
  google:
  baidu:

analytics: # 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La统计、百度统计
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

comment: valine # 评论框，目前仅支持 valine

valine: 
  appId: <API_ID> # leancloud application app id
  appKey: <API_Key> # leancloud application app key
  serverURLs: <REST_API_URL> # leancloud rest api url, for example: https://blablabla.api.lncldglobal.com
  visitor: false # 文章访问量统计
  requiredFields: [nick,mail] #设置必填项，v1.4.6+可用
  placeholder: 此处留言~ 填写邮箱可以接收回复提醒 # 评论框占位提示符
  verify: false # 验证码服务，v1.4.0+ 已废弃
  recordIP: false # 是否记录评论者IP，开启有可能会导致变慢

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'



# achive widget behavior
widgetAchive: #文章归档组件
  archive_type: 'year' #按月展示还是按年展示
  show_count: true  #是否展示数量

widgetLink: #链接组件
  - title: <title>
    img : <img_path>
    link : <url>
  - title: <title>
    img : <img_path>
    link : <url>

highlight: prismjs #高亮系统，可选prismjs、hljs
